services:
  rpsd-ingest:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      target: development
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project      
      - ../../:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    # It seems to be ignored, though!!!
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - rpsd-ingest-dapr
    network_mode: "service:rpsd-ingest-dapr"

  ############################
  # Dapr sidecar
  ############################
  rpsd-ingest-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "-app-id", "rpsd-ingest",
      "-placement-host-address", "placement:50006",
      "-scheduler-host-address", "scheduler:50007",
      "-resources-path", "/components"]
    volumes:
      - "../src/rpsd_ingest/components/:/components"
      - type: bind
        source: ../src/rpsd_ingest/components/
        target: /components
        bind:
          create_host_path: false
    networks:
      - rpsd-dapr

############################
# Network between containers
############################
networks:
  rpsd-dapr:
    external: true
    name: rpsd-dapr