services:
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - rpsd-dapr

  ############################
  # Dapr scheduler service
  ############################
  scheduler:
    image: "daprio/dapr"
    command: ["./scheduler", "--port", "50007", "--etcd-data-dir", "/data"]
    ports:
      - "50007:50007"
    networks:
      - rpsd-dapr
    user: root
    volumes:
      - "../mnt/dapr-etcd-data/:/data"

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - rpsd-dapr
############################
# Network between containers
############################
networks:
  rpsd-dapr:
    name: rpsd-dapr