services:
  rpsd-ingest:
    extends:
      file: ./docker-compose-base.yml
      service: rpsd-ingest
    command: ["uv", "run", "--directory", "/workspaces/rpsd-ingest", "app"]
    #command: /bin/sh -c "sleep 0s; echo 'PIPPO!!!'"
